{"index":{"_index":"rp_2","_id":1}}
{"launch_id":1234567892,"launch_name":"Launch with test items with logs","launch_number":0,"launch_start_time":"2020-01-15 10:57:43","test_item":1,"test_item_name":"first test","unique_id":"unique1","cluster_id":"0","cluster_message":"","test_case_hash":-1126886180,"is_auto_analyzed":false,"issue_type":"ti001","log_time":"2020-01-15 10:57:43","log_level":40000,"original_message_lines":3,"original_message_words_number":8,"message":" Message     \n java.lang.reflect.Method.invoke(Method.java : ) \n message error caused by exception","is_merged":false,"start_time":"2020-01-15 10:57:43","merged_small_logs":"","detected_message":" Message     \n message error caused by exception","detected_message_with_numbers":" Message  1   \n message error caused by exception","stacktrace":" java.lang.reflect.Method.invoke(Method.java : ) ","only_numbers":"1","found_exceptions":"","whole_message":"Message 1 \n message error caused by exception \n  java.lang.reflect.Method.invoke(Method.java:) ","potential_status_codes":"","found_tests_and_methods":"","cluster_with_numbers":false,"urls":"","paths":"","message_params":"","found_exceptions_extended":"","detected_message_extended":" Message     \n message error caused by exception","detected_message_without_params_extended":"Message  \n message error caused by exception","stacktrace_extended":" java.lang.reflect.Method.invoke Method.invoke invoke (Method.java : ) ","message_extended":" Message     \n java.lang.reflect.Method.invoke Method.invoke invoke (Method.java : ) \n message error caused by exception","message_without_params_extended":"Message  \n java.lang.reflect.Method.invoke Method.invoke invoke (Method.java : ) \n message error caused by exception","detected_message_without_params_and_brackets":"Message  \n message error caused by exception","message_without_params_and_brackets":"Message  \n java.lang.reflect.Method.invoke \n message error caused by exception"}
