[{
  "launchId": 1234567892,
  "project": 2,
    "launchName": "Launch with test items with logs",
    "launchStartTime": [2020,1,15,10,57,43],
    "testItems": [
        {
            "uniqueId": "unique1",
            "testItemId": 1,
            "testCaseHash": -1126886180,
            "issueType": "ti001",
            "startTime": [2020,1,15,10,57,43],
            "testItemName": "first test",
            "isAutoAnalyzed": false,
            "logs": [
                {
                  "logId": 1,
                    "logLevel": 40000,
                    "logTime": [2020,1,15,10,57,43],
                    "message": "<html>Message <b>1</b></html> \n java.lang.reflect.Method.invoke(Method.java:498) \n message error caused by exception\n ... 34 more"
                },
                {
                  "logId": 3,
                    "logLevel": 30000,
                    "logTime": [2020,1,15,10,57,43],
                    "message": "Message 3"
                }
            ]
        }
    ]
}]
